name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout RIOT
        uses: actions/checkout@v2
        with:
          repository: 'RIOT-OS/RIOT'
          path: RIOT
      - name: Fetch statistics
        run: |
          ls -l RIOT/boards | grep "^d" | grep -v "common" | wc -l > riot_stats.txt
          cat riot_stats.txt
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - name: Deploy
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: _site/
          remote_path: /var/www/demo/
          remote_host: alamos.cc
          remote_user: revamp
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
