name: Deployment

on:
  schedule:
    # every day at 2:00
    - cron: '0 0 2 * * ?'
  push:
    branches:
      - master
      - actions_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout RIOT
        uses: actions/checkout@v2
        with:
          repository: 'RIOT-OS/RIOT'
          path: _RIOT
          fetch-depth: 0
      - name: Fetch boards
        working-directory: ${{ github.workspace }}/_RIOT
        run: |
          ls -l boards | grep "^d" | grep -v "common" | wc -l | xargs printf "boards: %d\n" > ${{ github.workspace }}/_data/riot_stats.yml
      - name: Fetch CPUs
        working-directory: ${{ github.workspace }}/_RIOT
        run: |
          git grep "config CPU_FAM_" | grep "Kconfig" | wc -l | xargs printf "cpus: %d\n" >> ${{ github.workspace }}/_data/riot_stats.yml
      - name: Fetch commits
        working-directory: ${{ github.workspace }}/_RIOT
        run: |
          git rev-list --count master | xargs printf "commits: %d\n" >> ${{ github.workspace }}/_data/riot_stats.yml
      - name: Fetch contributors
        working-directory: ${{ github.workspace }}/_RIOT
        run: |
          git log --pretty=format:"%s" --merges | awk -F " " '/pull/ {match($NF, "(\\w*)", a); print a[1]}' | sort -u | wc -l | xargs printf "contributors: %d\n" >> ${{ github.workspace }}/_data/riot_stats.yml
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - name: Deploy
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: _site/
          remote_path: /var/www/demo/
          remote_host: alamos.cc
          remote_user: revamp
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
