name: Deployment

on:
  push:
    branches:
      - master
      - actions_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout RIOT
        uses: actions/checkout@v2
        with:
          repository: 'RIOT-OS/RIOT'
          path: _RIOT
          fetch-depth: 0
      - name: Fetch statistics
        working-directory: ${{ github.workspace }}/_RIOT
        run: |
          ls -l boards | grep "^d" | grep -v "common" > boards.txt
          wc -l boards.txt | printf "boards: %d\n"> ${{ github.workspace }}/_data/riot_stats.yml
          git grep "config CPU_FAM_" | grep "Kconfig" > cpus.txt
          wc -l cpus.txt | printf "cpus: %d\n" >> ${{ github.workspace }}/_data/riot_stats.yml
          git rev-list --count master | printf "commits: %d\n" >> ${{ github.workspace }}/_data/riot_stats.yml
          git log --pretty=format:"%s" --merges | awk -F " " '/pull/ {match($NF, "(\\w*)", a); print a[1]}' | sort -u > contributors.txt
          wc -l contributors.txt | printf "contributors: %d\n" >> ${{ github.workspace }}/_data/riot_stats.yml
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - name: Deploy
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: _site/
          remote_path: /var/www/demo/
          remote_host: alamos.cc
          remote_user: revamp
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
