name: Preview PR

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  preview:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install surge
        run: npm --global install surge

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.event.workflow_run.run_id }}
          name: site

      - name: Deploy PR preview
        run: |
          surge ./_site ${{ github.repository_owner}}-riot-os-org-preview-${{ github.event.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Comment URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            🚀 PR preview deployed to <https://${{ github.repository_owner}}-riot-os-org-preview-${{ github.event.number }}.surge.sh>
